@UserManagementApi_HostAddress = https://localhost:7018

GET {{UserManagementApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{UserManagementApi_HostAddress}}/api/user/create-user
Content-Type: application/json

{
  "userName": "adrianezacari",
  "password": "testingngpassword",
  "email": "adriane.zacari@test.com"
}

###
